#
# this file provides configuration for Travis Continuous Integration
# written by Sam-Mauris Yong
#

language: php
php:
  - 5.3
  - 5.3.3
  - 5.4
before_script:
  - composer install
  - pecl install memcache
  - echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
script: phpunit -c phpunit.xml.dist